SELECT barang.KODEBRG, barang.NAMABRG, COALESCE(SUM(jual.JUMLAH), 0) AS JML_JUAL
FROM BARANG barang
LEFT JOIN JUAL jual ON barang.KODEBRG = jual.KODEBRG
GROUP BY barang.KODEBRG, barang.NAMABRG
ORDER BY JML_JUAL DESC;
